hash-format = "sha256"

[[files]]
file = "mods/connector.pw.toml"
hash = "0a4d0034c5a1379d5aa57c0a104aaa2adbb98f1e2b89d4ec0b7ef68df2e16a1a"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "c604862c7db098f8edcfa6aa1ebc4e235b3008fdbc61450c0da9c3c234513a54"
metafile = true
