name = "Friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a87b4c5760bea50bab69c8da4cdc18ae1ffb421b4605e4e45977250d028ac72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21.1"]
