name = "Friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2a5e60e0558275651bcc323d2b59ede8ff7fb5f98c7c1971c5b937c4ac1c1d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"

[options]
acceptable-game-versions = ["1.21.1"]
