name = "Friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f14bd4b16ddd552f91643a2428cee70912f8e41155f1764f0fdc2f9fe4636cee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"

[options]
acceptable-game-versions = ["1.21.1"]
