name = "Friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "954d6cc6d69cd86088bfcbab8a8053754542f8bd733d25fec32b4068e9f41ad8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"

[options]
acceptable-game-versions = ["1.21.1"]
