name = "Friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80695d58499a9d10f586cda6ba486bb8c6c58a2437f0f3781602ca43f4045763"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"

[options]
acceptable-game-versions = ["1.21.1"]
