name = "Friends Modpack"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bb05e8db9e975450ce130e6c623204b4749d190f82ba217b2e90e5bf445d269"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21.1"]
