name = "Friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a51b4d792217cfb4c8e3671bcbd50464909a1ee5581a22a02027e825bc7fb2f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"

[options]
acceptable-game-versions = ["1.21.1"]
